/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CostRouteImport } from './routes/cost'
import { Route as GovernanceMapRouteImport } from './routes/governance-map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AuditIndexRouteImport } from './routes/audit.index'
import { Route as AuditRequestIdRouteImport } from './routes/audit.$requestId'
import { Route as InvestigationsEventIdRouteImport } from './routes/investigations.$eventId'
import { Route as PoliciesIndexRouteImport } from './routes/policies.index'
import { Route as PoliciesBuilderRouteImport } from './routes/policies.builder'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as SecurityEventsRouteImport } from './routes/security.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceMapRoute = GovernanceMapRouteImport.update({
  id: '/governance-map',
  path: '/governance-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditRoute,
} as any)
const AuditRequestIdRoute = AuditRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => AuditRoute,
} as any)
const InvestigationsEventIdRoute = InvestigationsEventIdRouteImport.update({
  id: '/investigations/$eventId',
  path: '/investigations/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PoliciesRoute,
} as any)
const PoliciesBuilderRoute = PoliciesBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => PoliciesRoute,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityEventsRoute = SecurityEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SecurityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRouteWithChildren
  '/cost': typeof CostRoute
  '/governance-map': typeof GovernanceMapRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/audit/$requestId': typeof AuditRequestIdRoute
  '/investigations/$eventId': typeof InvestigationsEventIdRoute
  '/policies/builder': typeof PoliciesBuilderRoute
  '/security/events': typeof SecurityEventsRoute
  '/audit/': typeof AuditIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cost': typeof CostRoute
  '/governance-map': typeof GovernanceMapRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/audit/$requestId': typeof AuditRequestIdRoute
  '/investigations/$eventId': typeof InvestigationsEventIdRoute
  '/policies/builder': typeof PoliciesBuilderRoute
  '/security/events': typeof SecurityEventsRoute
  '/audit': typeof AuditIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/security': typeof SecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRouteWithChildren
  '/cost': typeof CostRoute
  '/governance-map': typeof GovernanceMapRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/audit/$requestId': typeof AuditRequestIdRoute
  '/investigations/$eventId': typeof InvestigationsEventIdRoute
  '/policies/builder': typeof PoliciesBuilderRoute
  '/security/events': typeof SecurityEventsRoute
  '/audit/': typeof AuditIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/cost'
    | '/governance-map'
    | '/login'
    | '/models'
    | '/policies'
    | '/security'
    | '/users'
    | '/workspace'
    | '/audit/$requestId'
    | '/investigations/$eventId'
    | '/policies/builder'
    | '/security/events'
    | '/audit/'
    | '/policies/'
    | '/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/cost'
    | '/governance-map'
    | '/login'
    | '/models'
    | '/users'
    | '/workspace'
    | '/audit/$requestId'
    | '/investigations/$eventId'
    | '/policies/builder'
    | '/security/events'
    | '/audit'
    | '/policies'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/cost'
    | '/governance-map'
    | '/login'
    | '/models'
    | '/policies'
    | '/security'
    | '/users'
    | '/workspace'
    | '/audit/$requestId'
    | '/investigations/$eventId'
    | '/policies/builder'
    | '/security/events'
    | '/audit/'
    | '/policies/'
    | '/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRouteWithChildren
  CostRoute: typeof CostRoute
  GovernanceMapRoute: typeof GovernanceMapRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  PoliciesRoute: typeof PoliciesRouteWithChildren
  SecurityRoute: typeof SecurityRouteWithChildren
  UsersRoute: typeof UsersRoute
  WorkspaceRoute: typeof WorkspaceRoute
  InvestigationsEventIdRoute: typeof InvestigationsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance-map': {
      id: '/governance-map'
      path: '/governance-map'
      fullPath: '/governance-map'
      preLoaderRoute: typeof GovernanceMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/$requestId': {
      id: '/audit/$requestId'
      path: '/$requestId'
      fullPath: '/audit/$requestId'
      preLoaderRoute: typeof AuditRequestIdRouteImport
      parentRoute: typeof AuditRoute
    }
    '/investigations/$eventId': {
      id: '/investigations/$eventId'
      path: '/investigations/$eventId'
      fullPath: '/investigations/$eventId'
      preLoaderRoute: typeof InvestigationsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/policies/builder': {
      id: '/policies/builder'
      path: '/builder'
      fullPath: '/policies/builder'
      preLoaderRoute: typeof PoliciesBuilderRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/security/': {
      id: '/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/events': {
      id: '/security/events'
      path: '/events'
      fullPath: '/security/events'
      preLoaderRoute: typeof SecurityEventsRouteImport
      parentRoute: typeof SecurityRoute
    }
  }
}

interface AuditRouteChildren {
  AuditRequestIdRoute: typeof AuditRequestIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditRequestIdRoute: AuditRequestIdRoute,
  AuditIndexRoute: AuditIndexRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

interface PoliciesRouteChildren {
  PoliciesBuilderRoute: typeof PoliciesBuilderRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
}

const PoliciesRouteChildren: PoliciesRouteChildren = {
  PoliciesBuilderRoute: PoliciesBuilderRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
}

const PoliciesRouteWithChildren = PoliciesRoute._addFileChildren(
  PoliciesRouteChildren,
)

interface SecurityRouteChildren {
  SecurityEventsRoute: typeof SecurityEventsRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityEventsRoute: SecurityEventsRoute,
  SecurityIndexRoute: SecurityIndexRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRouteWithChildren,
  CostRoute: CostRoute,
  GovernanceMapRoute: GovernanceMapRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  PoliciesRoute: PoliciesRouteWithChildren,
  SecurityRoute: SecurityRouteWithChildren,
  UsersRoute: UsersRoute,
  WorkspaceRoute: WorkspaceRoute,
  InvestigationsEventIdRoute: InvestigationsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}